### ISSUE TITLE
Standardise BLUFOR Load-outs

### ISSUE THREAD

**Issue by NatPro38** [bug-quota-code/arma3-maps#83]
I think it may help if we had a standard team load-out/composition for use when creating missions. I think updating and using those from Lost and Found would work best as we often have a helicopter.
I also think we should have crates with standardised inventory's for equipping the team and have the team have a default weapon at start e.g. m4a1, except AR of course.
So team composition:
Phoenix
- FTL: M4A1
- AR: M249
- ARAG: M4A1
- MED: M4A1
- R: M4A1
- RAT: M4A1 + some disposable Launcher
- FAC: M4A1

Gully
- HPilot: M4A1
- HCrew: M4A1

**Comment by curiousinternals** [comment]
I agree with this. Perhaps at some point we could discuss exactly what equipment should be picked. I'd also like to do this for other factions.

I'm also going to be updating the Chernarus sandbox with any standard code and data produced, so I can use it as a template for creating new missions.

**Comment by curiousinternals** [comment]
Loadouts decided on, just need to convert them and add them to the sandbox. Standard fireteam composition set as well:
- 1 * ftl
- 1 * ar
- 1* arag
- 3 * r

Additional equipment gets attached to the riflemen.

**Comment by curiousinternals** [comment]
No conversion needed.
